const express = require("express")
const cors = require("cors")
const app = express()
const userRouter = require("./router/user")
const categoryRouter = require("./router/category")
const productsRouter = require("./router/products")
const cartRouter = require("./router/cart")
const addressesRouter = require("./router/addresses")
const placeorderRouter = require("./router/placeorder")
// const movieRouter = require("./router/movie")
// const shareRouter = require("./router/share")

app.use(cors("*"))
app.use(express.json())
// app.use(express.static("uploads"))

app.use("/user", userRouter)
app.use("/category", categoryRouter)
app.use("/products", productsRouter)
app.use("/cart",cartRouter)
app.use("/address",addressesRouter)
app.use("/placeorder",placeorderRouter)
// app.use("/movie", movieRouter)
// app.use("/share", shareRouter)

app.listen(9898, "0.0.0.0", () => {
  console.log("Server started on port 9898")
})
